In [26]:
# Rand-Select (with linear expected running time)
# author: yifan zhu
import random

def partition(arr, p, r):
    q = arr[r]
    i = p - 1
    for j in range(p, r):
        if arr[j] <= q:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[r] = arr[r], arr[i + 1]
    return i + 1

def randomized_partition(arr, p, r):
    q = random.randint(p, r)
    arr[q], arr[r] = arr[r], arr[q]
    return partition(arr, p, r)

def rand_select(arr, p, r, i):
    if p == r:
        return arr[p]
    q = randomized_partition(arr, p, r)
    k = q - p + 1
    if k == i:
        return arr[q]
    elif i < k:
        return rand_select(arr, p, q - 1, i)
    else:
        return rand_select(arr, q + 1, r, i - k)

In [24]:
A = list(range(1, 101))
random.shuffle(A)
sorted_A = sorted(A)
print("Random array A:")
print(A)
for order in range(1, len(A) + 1):
    result = rand_select(A.copy(), 0, len(A) - 1, order)
    expected = sorted_A[order - 1]
    print(f"The {order}th smallest element in A: select returns {result}, expected {expected}")

Random array A:
[36, 43, 41, 13, 11, 34, 99, 25, 12, 44, 65, 67, 42, 56, 76, 69, 3, 14, 45, 53, 87, 58, 27, 7, 66, 48, 75, 33, 50, 79, 10, 31, 96, 74, 54, 37, 68, 81, 16, 5, 20, 91, 89, 1, 28, 57, 98, 90, 30, 29, 72, 46, 83, 63, 71, 82, 78, 2, 92, 85, 93, 23, 49, 6, 60, 32, 94, 21, 38, 55, 8, 26, 22, 70, 77, 62, 73, 15, 97, 40, 47, 24, 35, 39, 9, 19, 95, 88, 80, 51, 17, 61, 100, 84, 64, 59, 4, 86, 18, 52]
The 1th smallest element in A: select returns 1, expected 1
The 2th smallest element in A: select returns 2, expected 2
The 3th smallest element in A: select returns 3, expected 3
The 4th smallest element in A: select returns 4, expected 4
The 5th smallest element in A: select returns 5, expected 5
The 6th smallest element in A: select returns 6, expected 6
The 7th smallest element in A: select returns 7, expected 7
The 8th smallest element in A: select returns 8, expected 8
The 9th smallest element in A: select returns 9, expected 9
The 10th smallest element in A: select returns 10, expected 10
The 11th smallest element in A: select returns 11, expected 11
The 12th smallest element in A: select returns 12, expected 12
The 13th smallest element in A: select returns 13, expected 13
The 14th smallest element in A: select returns 14, expected 14
The 15th smallest element in A: select returns 15, expected 15
The 16th smallest element in A: select returns 16, expected 16
The 17th smallest element in A: select returns 17, expected 17
The 18th smallest element in A: select returns 18, expected 18
The 19th smallest element in A: select returns 19, expected 19
The 20th smallest element in A: select returns 20, expected 20
The 21th smallest element in A: select returns 21, expected 21
The 22th smallest element in A: select returns 22, expected 22
The 23th smallest element in A: select returns 23, expected 23
The 24th smallest element in A: select returns 24, expected 24
The 25th smallest element in A: select returns 25, expected 25
The 26th smallest element in A: select returns 26, expected 26
The 27th smallest element in A: select returns 27, expected 27
The 28th smallest element in A: select returns 28, expected 28
The 29th smallest element in A: select returns 29, expected 29
The 30th smallest element in A: select returns 30, expected 30
The 31th smallest element in A: select returns 31, expected 31
The 32th smallest element in A: select returns 32, expected 32
The 33th smallest element in A: select returns 33, expected 33
The 34th smallest element in A: select returns 34, expected 34
The 35th smallest element in A: select returns 35, expected 35
The 36th smallest element in A: select returns 36, expected 36
The 37th smallest element in A: select returns 37, expected 37
The 38th smallest element in A: select returns 38, expected 38
The 39th smallest element in A: select returns 39, expected 39
The 40th smallest element in A: select returns 40, expected 40
The 41th smallest element in A: select returns 41, expected 41
The 42th smallest element in A: select returns 42, expected 42
The 43th smallest element in A: select returns 43, expected 43
The 44th smallest element in A: select returns 44, expected 44
The 45th smallest element in A: select returns 45, expected 45
The 46th smallest element in A: select returns 46, expected 46
The 47th smallest element in A: select returns 47, expected 47
The 48th smallest element in A: select returns 48, expected 48
The 49th smallest element in A: select returns 49, expected 49
The 50th smallest element in A: select returns 50, expected 50
The 51th smallest element in A: select returns 51, expected 51
The 52th smallest element in A: select returns 52, expected 52
The 53th smallest element in A: select returns 53, expected 53
The 54th smallest element in A: select returns 54, expected 54
The 55th smallest element in A: select returns 55, expected 55
The 56th smallest element in A: select returns 56, expected 56
The 57th smallest element in A: select returns 57, expected 57
The 58th smallest element in A: select returns 58, expected 58
The 59th smallest element in A: select returns 59, expected 59
The 60th smallest element in A: select returns 60, expected 60
The 61th smallest element in A: select returns 61, expected 61
The 62th smallest element in A: select returns 62, expected 62
The 63th smallest element in A: select returns 63, expected 63
The 64th smallest element in A: select returns 64, expected 64
The 65th smallest element in A: select returns 65, expected 65
The 66th smallest element in A: select returns 66, expected 66
The 67th smallest element in A: select returns 67, expected 67
The 68th smallest element in A: select returns 68, expected 68
The 69th smallest element in A: select returns 69, expected 69
The 70th smallest element in A: select returns 70, expected 70
The 71th smallest element in A: select returns 71, expected 71
The 72th smallest element in A: select returns 72, expected 72
The 73th smallest element in A: select returns 73, expected 73
The 74th smallest element in A: select returns 74, expected 74
The 75th smallest element in A: select returns 75, expected 75
The 76th smallest element in A: select returns 76, expected 76
The 77th smallest element in A: select returns 77, expected 77
The 78th smallest element in A: select returns 78, expected 78
The 79th smallest element in A: select returns 79, expected 79
The 80th smallest element in A: select returns 80, expected 80
The 81th smallest element in A: select returns 81, expected 81
The 82th smallest element in A: select returns 82, expected 82
The 83th smallest element in A: select returns 83, expected 83
The 84th smallest element in A: select returns 84, expected 84
The 85th smallest element in A: select returns 85, expected 85
The 86th smallest element in A: select returns 86, expected 86
The 87th smallest element in A: select returns 87, expected 87
The 88th smallest element in A: select returns 88, expected 88
The 89th smallest element in A: select returns 89, expected 89
The 90th smallest element in A: select returns 90, expected 90
The 91th smallest element in A: select returns 91, expected 91
The 92th smallest element in A: select returns 92, expected 92
The 93th smallest element in A: select returns 93, expected 93
The 94th smallest element in A: select returns 94, expected 94
The 95th smallest element in A: select returns 95, expected 95
The 96th smallest element in A: select returns 96, expected 96
The 97th smallest element in A: select returns 97, expected 97
The 98th smallest element in A: select returns 98, expected 98
The 99th smallest element in A: select returns 99, expected 99
The 100th smallest element in A: select returns 100, expected 100

In [19]:
# Select (with linear worst-case running time)
import random

def partition(arr, p, r, x):
    # Assume the elements in arr are unique and that x is in arr[p:r+1]
    pivot_index = arr.index(x)
    arr[pivot_index], arr[r] = arr[r], arr[pivot_index]
    q = arr[r]
    i = p - 1
    for j in range(p, r):
        if arr[j] <= q:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[r] = arr[r], arr[i + 1]
    return i + 1

def select(arr, p, r, i):
    if p == r:
        return arr[p]
    if r - p + 1 <= 5:
        return sorted(arr[p:r+1])[i-1]
    
    while (r - p + 1) % 5 != 0:
        for j in range(p + 1, r + 1):
            if arr[p] > arr[j]:
                arr[p], arr[j] = arr[j], arr[p]
        if i == 1:
            return arr[p]
        p += 1
        i -= 1
    
    g = (r - p + 1) // 5
    # For each group of 5 elements, place the median of the group in the middle position
    for j in range(p, p + g * 5, 5):
        sub_list = sorted(arr[j:j+5])
        arr[j + 2] = sub_list[2]
    
    x = select(arr, p + 2 * g, p + 3 * g - 1, (g + 1) // 2)
    q = partition(arr, p, r, x)
    k = q - p + 1
    
    if i == k:
        return arr[q]
    elif i < k:
        return select(arr, p, q - 1, i)
    else:
        return select(arr, q + 1, r, i - k)

# test 

A = list(range(1, 101))
random.shuffle(A)
sorted_A = sorted(A)
print("Random array A:")
print(A)
for order in range(1, len(A) + 1):
    result = select(A.copy(), 0, len(A) - 1, order)
    expected = sorted_A[order - 1]
    print(f"The {order}th smallest element in A: select returns {result}, expected {expected}")

Random array A:
[54, 74, 11, 49, 2, 27, 53, 79, 56, 75, 82, 26, 8, 24, 73, 33, 38, 96, 60, 34, 16, 28, 58, 77, 35, 5, 71, 47, 98, 17, 1, 89, 42, 84, 46, 31, 37, 18, 86, 100, 13, 9, 78, 91, 93, 50, 22, 45, 99, 92, 87, 39, 67, 97, 15, 95, 12, 30, 66, 14, 52, 88, 6, 4, 85, 59, 25, 21, 41, 20, 51, 65, 3, 43, 70, 94, 7, 55, 80, 29, 64, 10, 76, 23, 19, 63, 44, 81, 72, 61, 83, 32, 62, 40, 48, 69, 57, 90, 36, 68]
The 1th smallest element in A: select returns 1, expected 1
The 2th smallest element in A: select returns 5, expected 2
The 3th smallest element in A: select returns 10, expected 3
The 4th smallest element in A: select returns 12, expected 4
The 5th smallest element in A: select returns 13, expected 5
The 6th smallest element in A: select returns 13, expected 6
The 7th smallest element in A: select returns 16, expected 7
The 8th smallest element in A: select returns 17, expected 8
The 9th smallest element in A: select returns 19, expected 9
The 10th smallest element in A: select returns 19, expected 10
The 11th smallest element in A: select returns 20, expected 11
The 12th smallest element in A: select returns 22, expected 12
The 13th smallest element in A: select returns 22, expected 13
The 14th smallest element in A: select returns 23, expected 14
The 15th smallest element in A: select returns 23, expected 15
The 16th smallest element in A: select returns 24, expected 16
The 17th smallest element in A: select returns 25, expected 17
The 18th smallest element in A: select returns 25, expected 18
The 19th smallest element in A: select returns 26, expected 19
The 20th smallest element in A: select returns 28, expected 20
The 21th smallest element in A: select returns 28, expected 21
The 22th smallest element in A: select returns 29, expected 22
The 23th smallest element in A: select returns 30, expected 23
The 24th smallest element in A: select returns 31, expected 24
The 25th smallest element in A: select returns 31, expected 25
The 26th smallest element in A: select returns 32, expected 26
The 27th smallest element in A: select returns 32, expected 27
The 28th smallest element in A: select returns 33, expected 28
The 29th smallest element in A: select returns 33, expected 29
The 30th smallest element in A: select returns 33, expected 30
The 31th smallest element in A: select returns 33, expected 31
The 32th smallest element in A: select returns 34, expected 32
The 33th smallest element in A: select returns 34, expected 33
The 34th smallest element in A: select returns 34, expected 34
The 35th smallest element in A: select returns 36, expected 35
The 36th smallest element in A: select returns 36, expected 36
The 37th smallest element in A: select returns 38, expected 37
The 38th smallest element in A: select returns 39, expected 38
The 39th smallest element in A: select returns 39, expected 39
The 40th smallest element in A: select returns 40, expected 40
The 41th smallest element in A: select returns 41, expected 41
The 42th smallest element in A: select returns 46, expected 42
The 43th smallest element in A: select returns 46, expected 43
The 44th smallest element in A: select returns 46, expected 44
The 45th smallest element in A: select returns 47, expected 45
The 46th smallest element in A: select returns 47, expected 46
The 47th smallest element in A: select returns 48, expected 47
The 48th smallest element in A: select returns 48, expected 48
The 49th smallest element in A: select returns 48, expected 49
The 50th smallest element in A: select returns 49, expected 50
The 51th smallest element in A: select returns 49, expected 51
The 52th smallest element in A: select returns 50, expected 52
The 53th smallest element in A: select returns 51, expected 53
The 54th smallest element in A: select returns 51, expected 54
The 55th smallest element in A: select returns 52, expected 55
The 56th smallest element in A: select returns 53, expected 56
The 57th smallest element in A: select returns 54, expected 57
The 58th smallest element in A: select returns 56, expected 58
The 59th smallest element in A: select returns 57, expected 59
The 60th smallest element in A: select returns 59, expected 60
The 61th smallest element in A: select returns 60, expected 61
The 62th smallest element in A: select returns 63, expected 62
The 63th smallest element in A: select returns 63, expected 63
The 64th smallest element in A: select returns 63, expected 64
The 65th smallest element in A: select returns 64, expected 65
The 66th smallest element in A: select returns 64, expected 66
The 67th smallest element in A: select returns 64, expected 67
The 68th smallest element in A: select returns 65, expected 68
The 69th smallest element in A: select returns 65, expected 69
The 70th smallest element in A: select returns 66, expected 70
The 71th smallest element in A: select returns 68, expected 71
The 72th smallest element in A: select returns 68, expected 72
The 73th smallest element in A: select returns 68, expected 73
The 74th smallest element in A: select returns 68, expected 74
The 75th smallest element in A: select returns 68, expected 75
The 76th smallest element in A: select returns 69, expected 76
The 77th smallest element in A: select returns 70, expected 77
The 78th smallest element in A: select returns 72, expected 78
The 79th smallest element in A: select returns 73, expected 79
The 80th smallest element in A: select returns 77, expected 80
The 81th smallest element in A: select returns 77, expected 81
The 82th smallest element in A: select returns 78, expected 82
The 83th smallest element in A: select returns 80, expected 83
The 84th smallest element in A: select returns 80, expected 84
The 85th smallest element in A: select returns 82, expected 85
The 86th smallest element in A: select returns 83, expected 86
The 87th smallest element in A: select returns 84, expected 87
The 88th smallest element in A: select returns 85, expected 88
The 89th smallest element in A: select returns 86, expected 89
The 90th smallest element in A: select returns 88, expected 90
The 91th smallest element in A: select returns 88, expected 91
The 92th smallest element in A: select returns 88, expected 92
The 93th smallest element in A: select returns 91, expected 93
The 94th smallest element in A: select returns 93, expected 94
The 95th smallest element in A: select returns 94, expected 95
The 96th smallest element in A: select returns 95, expected 96
The 97th smallest element in A: select returns 98, expected 97
The 98th smallest element in A: select returns 98, expected 98
The 99th smallest element in A: select returns 99, expected 99
The 100th smallest element in A: select returns 100, expected 100